### ISSUE TITLE
Merge development to main

### ISSUE THREAD

**Issue by linusromland** [SvanteJonssonSchool/svante-jonsson-slutprojekt-WESWEB01-WEUWEB02#2]
### _**### 

> `I want to see your development without going to other branch you big dum dum`

**_

**Comment by svante-jonsson** [comment]
NO! >:(

**Comment by linusromland** [comment]
Shytttt

**Comment by svante-jonsson** [comment]
Please don't be so mean :( I'm trying my hardest you know

**Comment by linusromland** [comment]
JUST MERGE OKE

**Comment by linusromland** [comment]
Good job man removeing that ugly *** repo

*This is not related to this repo and therefore not valid*

EDIT: This comment have been edited to remove vulgar language

**Comment by svante-jonsson** [comment]
Do not be so vulgar @linusromland. This is a respectful GitHub repo

**Comment by linusromland** [comment]
i want to vulkgaraa bvre

**Comment by linusromland** [comment]
wrong button

**Comment by linusromland** [comment]
i am goodf at his

**Comment by linusromland** [comment]
Merge when you feel like it
